# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17fY_bAibj7_yRFIe4-U77rQGFC4wWcLE
"""

# prompt: Hazme un codigo que me pregunte el nombre y la edad
name = input("¿Cuál es tu name? ")
age = input("¿Cuál es tu edad? ")

print(f"Hola, {name}. Tienes {age} años.")



